version: "3.5"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    volumes:
      - "./etc/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - kohana

  php-fpm:
    image: webdevops/php-dev:5.6
    hostname: php-fpm
    volumes:
      - "./www:/www"
      - "./etc/php/php.ini:/usr/local/etc/php/php.ini"
    working_dir: "/www"
    depends_on:
      - mysql
    networks:
      - kohana

  nginx:
    image: webdevops/nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - "./www:/www"
    - "./etc/nginx/:/etc/nginx/conf.d/"
    - "./logs:/var/log/nginx"
    depends_on:
      - php-fpm
      - mysql
    networks:
      - kohana

#  memcached:
#    image: memcached:latest
#    hostname: memcached
#    restart: unless-stopped
#    ports:
#      - "11211:11211"
#    networks:
#      - kohana
#    environment:
#      VIRTUAL_HOST: memcached.dev.loc

volumes:
  mysql-data:
    name: kohana_mysql_data

networks:
  kohana:
    driver: bridge

